name: Android CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build



  staticAnalysis:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Static Analysis
        run: ./gradlew  detekt

      - name: Upload Static Analysis Report
        uses: actions/upload-artifact@v2.2.0
        if: ${{ always() }}
        with:
          name: Static Analysis Report
          path: |
            **/reports/
